version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: banco-de-dados
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql